# Generated by Django 5.2.15 on 2026-06-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeocodeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("display_name", models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.IntegerField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=4, max_digits=8)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="routing_fue_latitud_6dc999_idx",
                    ),
                    models.Index(
                        fields=["state", "price"], name="routing_fue_state_20ffed_idx"
                    ),
                ],
            },
        ),
    ]
